package problems041to050

//Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//
//Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
//Pentagonal	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
//Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
//It can be verified that T285 = P165 = H143 = 40755.
//
//Find the next triangle number that is also pentagonal and hexagonal.
object Problem45 
{
	def main(args: Array[String]) 
	{
		def triangle(n : Long) = (n * (n + 1)) / 2
		def pentagonal(n : Long) = (n * (3 * n - 1)) / 2
		def hexagonal(n : Long) = n * (2 * n - 1)
		
		var i = 143
		var curTri = 1
		var curPen = 1
		var cont = true

		while (cont)
		{
			i += 1
			val curHex = hexagonal(i)
			
			while(pentagonal(curPen) <= curHex) curPen += 1
			while(triangle(curTri) <= curHex) curTri += 1
			
			if (pentagonal(curPen) != curHex) curPen -= 1
			if (triangle(curTri) != curHex) curTri -= 1
			
			cont = (pentagonal(curPen) != triangle(curTri) && pentagonal(curPen) != curHex)
		}
		
		println(triangle(curTri) + " " + pentagonal(curPen) + " " + hexagonal(i))
		println(curTri + " " + curPen + " " + i)
	}
}