package problems001to010

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

object Problem02 
{
	def main(args: Array[String]) 
	{
		def fibbs(start : Int, end : Int) : Stream[Int] = (start + end) #:: fibbs(end, start + end) 
		var fib = 1 #:: 1 #:: fibbs(1, 1)
		println(fib.takeWhile(_ < 4000000).filter(_ % 2 == 0).sum)
	}

}